language: php
php:
- '7.1'
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache/files"
env:
- SYMFONY_VERSION="4.0.*" DB=sqlite
install:
- cp .env.dist .env
- composer install
script:
- bin/console app:data:import
notifications:
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
